cookietemple_version: '1.3.0 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: spapros
project_slug_no_hyphen: spapros
template_version: '2.0.0 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: theislab
creator_github_username: zethson
is_github_repo: true
is_repo_private: false
is_github_orga: true
github_orga: theislab
full_name: Lukas Heumos
email: lukas.heumos@posteo.net
project_name: spapros
project_short_description: Fully automated spatial transcriptomics probe selection.
version: 0.1.1
license: MIT
